// Task 1.4 exit criterion:
//
//   the full protocol core, driven by MockTransport replaying
//   Fixtures/clean-start.gvcap, emits the expected NAL sequence -- verified
//   against a reference NAL-type/length list extracted from the same
//   capture by a Python script.
//
// This wires together every piece built in tasks 1.1-1.4:
//   MockTransport (this task)     -- replays clean-start.gvcap, yielding
//                                     UDP:9003 payload bytes on `inbound`
//   WireProtocol.parseOuter (1.2/1.4) -- splits each payload into its
//                                     8-byte outer header + body, so we can
//                                     dispatch on pktType
//   FrameReassembler (1.3)        -- fed every pktType == 0x02 (video)
//                                     packet's body; emits a complete NAL
//                                     each time a frame's fragments finish
//
// and asserts the resulting {nalType, length} sequence matches
// Fixtures/clean_start_nal_reference.json, generated by
// Tools/gen_nal_reference.py from the same capture (see that script's
// header comment for why it's a faithful Python port of
// FrameReassembler's corrected algorithm rather than a re-use of
// stream.py's buggy inline logic).
//
// Pacing: `.immediate` (see MockTransport.Pacing's doc comment) -- this
// test cares about the emitted NAL *sequence*, not wall-clock timing, and
// clean-start.gvcap spans several real seconds; replaying it at recorded
// speed would make this test slow (and, under CI scheduling jitter,
// creates a small flakiness surface) for no benefit to what's actually
// being verified here.

import Testing
import Foundation
@testable import GogglesProtocol

private struct NALReferenceEntry: Decodable, Equatable {
    let nalType: UInt8
    let length: Int
}

private func loadNALReference() throws -> [NALReferenceEntry] {
    let url = FixturesLocation.url("clean_start_nal_reference.json")
    let data = try Data(contentsOf: url)
    return try JSONDecoder().decode([NALReferenceEntry].self, from: data)
}

@Test func fullPipelineOverCleanStartCaptureMatchesPythonNALReference() async throws {
    let reference = try loadNALReference()
    #expect(!reference.isEmpty, "reference fixture should be non-empty (regenerate with Tools/gen_nal_reference.py if this fails)")

    let transport = try MockTransport(
        capturePath: FixturesLocation.url("clean-start.gvcap"),
        pacing: .immediate
    )

    let reassembler = FrameReassembler()
    var emitted: [NALReferenceEntry] = []

    for await payload in transport.inbound {
        guard let outer = WireProtocol.parseOuter(payload) else { continue }
        guard outer.pktType == WireProtocol.packetTypeVideo else { continue }
        // `receivedAt` should be "now" at a real call site; here we don't
        // have a real wall clock driving replay (pacing is .immediate), so
        // Date() calls will all land within a few ms of each other. That's
        // fine for this test: clean-start.gvcap's expected sequence (per
        // the reference generator) never actually exercises the 250ms
        // time-based eviction path (dropped_frame_count == 0 when the
        // reference was generated using the *recorded* timestamps), so
        // using the real clock here instead of the recorded one does not
        // change which entries get evicted.
        guard let nal = reassembler.process(videoPayload: outer.body, receivedAt: Date()) else { continue }
        let nalType = nal[nal.startIndex + 4] & 0x1F // nal always starts with the 4-byte start code
        emitted.append(NALReferenceEntry(nalType: nalType, length: nal.count))
    }

    #expect(reassembler.droppedFrameCount == 0, "clean-start.gvcap is not expected to exercise fragment loss/eviction")
    #expect(emitted.count == reference.count)
    #expect(emitted == reference)
}
